const home = 0,
  table = 1,
  intro = 2,
  workPlan = 3,
  workFlow = 4,
  workTaskForce = 5,
  onsite = 6,
  organizationContact = 7,
  businessScenario = 8,
  borrowed_equipment = 9,
  energy = 10,
  fileTemplate = 11,
  enterpriseInfo = 12,
  expert = 13,
  meeting = 14,
  registrationInfo = 15,
  feedback = 16,
  system = 17;

export {
  home,
  table,
  intro,
  workPlan,
  workFlow,
  workTaskForce,
  onsite,
  expert,
  energy,
  fileTemplate,
  enterpriseInfo,
  organizationContact,
  businessScenario,
  borrowed_equipment,
  feedback,
  registrationInfo,
  meeting,
  system
};
